### ISSUE TITLE
Notification panel is white

### ISSUE THREAD

**Issue by Geobert** [StylishThemes/Discourse-Dark#33] opened 2020-05-28 16:00 UTC
* **Browser**:  Firefox Nightly
* **Operating System**:  windows 10
* **Link to page with the issue**: https://users.rust-lang.org/
* **Screenshot**:
![image](https://user-images.githubusercontent.com/72570/83164947-c4af8600-a104-11ea-9169-a6d0428cf0be.png)

**Comment by the-j0k3r** [comment] 2020-05-28 17:11
duplicate of #32

**Closed by the-j0k3r** 2020-05-28 17:11 UTC
Labels: bug :bug:
